- src: geerlingguy.java #https://github.com/geerlingguy/ansible-role-java
- src: cavemandaveman.nifi #https://github.com/cavemandaveman/ansible-role-nifi
- src: cavemandaveman.nifi_registry #https://github.com/cavemandaveman/ansible-role-nifi-registry
