---
- name: Download Java binary
  get_url:
    url: "{{ java.download_url}}/{{ java.version }}.tar.gz"
    dest: "/tmp/{{ java.version }}.tar.gz"

- name: Unpack Java binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/{{ java.version }}.tar.gz"
    dest: "{{ java.install_folder}}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    creates: "{{ java.install_folder }}/{{ java.version }}"

- name: Fix permissions
  file:
    path: "{{ java.install_folder }}/{{ java.version }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    recurse: "yes"

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "{{ java.install_folder }}/{{ java.version }}/bin/java" 2000'

- name: Clean up
  file: state=absent path="/tmp/{{ java.version }}.tar.gz"