---
- name: Download Java
  command: "echo hello"

# - name: Unpack archive
#   command: "tar -zxf {{java.java_archive}} -C {{java.download_folder}} creates={{java.java_name}}"

# - name: Fix ownership
#   file: state=directory path={{java.java_name}} owner=root group=root recurse=yes

# - name: Make Java available for system
#   command: 'alternatives --install "/usr/bin/java" "java" "{{java.java_name}}/bin/java" 2000'

# - name: Clean up
#   file: state=absent path={{java.java_archive}}