---
- name: Download NiFi binary
  get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.tar.gz"
    dest: "/tmp/nifi-{{ nifi_version }}-bin.tar.gz"

- name: Unpack NiFi binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/nifi-{{ nifi_version }}-bin.tar.gz"
    dest: "{{ nifi_config_dirs.install }}/"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    creates: "{{ nifi_config_dirs.install }}/nifi-{{ nifi_version }}"

- name: Fix permissions
  file:
    path: "{{ nifi_config_dirs.install }}/nifi-{{ nifi_version }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    recurse: "yes"

- name: Create NiFi symlink
  file:
    src: "nifi-{{ nifi_version }}"
    path: "{{ nifi_config_dirs.home }}"
    state: "link"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"