---
- name: Download NiFi toolkit binary
  get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-toolkit-{{ nifi_version }}-bin.tar.gz"
    dest: "/tmp/nifi-toolkit-{{ nifi_version }}-bin.tar.gz"

- name: Unpack NiFi toolkit binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/nifi-toolkit-{{ nifi_version }}-bin.tar.gz"
    dest: "{{ nifi_config_dirs.toolkit }}/"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    creates: "{{ nifi_config_dirs.toolkit }}/nifi-toolkit-{{ nifi_version }}"