---
- name: Download Java
  command: "wget --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' 'https://cdn.azul.com/zulu/bin/zulu8.50.0.51-ca-jdk8.0.275-linux_x64.tar.gz'"

# - name: Unpack archive
#   command: "tar -zxf {{java.java_archive}} -C {{java.download_folder}} creates={{java.java_name}}"

# - name: Fix ownership
#   file: state=directory path={{java.java_name}} owner=root group=root recurse=yes

# - name: Make Java available for system
#   command: 'alternatives --install "/usr/bin/java" "java" "{{java.java_name}}/bin/java" 2000'

# - name: Clean up
#   file: state=absent path={{java.java_archive}}