---
- name: Create install directory for Nifi
  file:
    path: "{{ nifi_config_dirs.install }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create install directory for Nifi Toolkit
  file:
    path: "{{ nifi_config_dirs.toolkit }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create shared resources directory
  file:
    path: "{{ nifi_config_dirs.external_config }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create cert directory
  file:
    path: "{{ nifi_config_dirs.external_config }}/ssl"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

# - name: Place keystore in cert directory
#   copy:
#     src: "env/{{ env_name }}/files/{{ ansible_fqdn }}.jks"
#     dest: "{{ nifi_config_dirs.external_config }}/ssl/{{ ansible_fqdn }}.jks"
#     owner: "{{ nifi_user }}"
#     group: "{{ nifi_group }}"

# - name: Place truststore in cert directory
#   copy:
#     src: "env/common/files/truststore.jks"
#     dest: "{{ nifi_config_dirs.external_config }}/ssl/truststore.jks"
#     owner: "{{ nifi_user }}"
#     group: "{{ nifi_group }}"
  
# - name: Place LDAP truststore in cert directory
#   copy:
#     src: env/common/files/ldap.jks
#     dest: "{{ nifi_config_dirs.external_config }}/ssl/ldap.jks"
#     owner: "{{ nifi_user }}"
#     group: "{{ nifi_group }}" 
