---
- hosts: nifi_registry_servers
  become: yes
  gather_facts: true
  pre_tasks:
    - name: "Prepare for NiFi Registry install"
      include: roles/augment-nifi-registry.yml
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk-devel
    - role: cavemandaveman.nifi_registry
  vars:
    nifi_registry_version: 0.4.0
    download_mirror_uri: http://apache.cs.utah.edu
    nifi_registry_user: svc_nifi
    nifi_registry_group: svc_nifigrp
    nifi_registry_config_dirs:
      install: /apps/nifi-registry/releases
      home: /apps/nifi-registry/releases/current
      external_config: /apps/nifi-registry/config_resources
    nifi_registry_properties:
      nifi.registry.web.http.host: ""
      nifi.registry.web.http.port: ""
      nifi.registry.web.https.host: "{{ ansible_fqdn }}"
      nifi.registry.web.https.port: 8443
      nifi.registry.security.keystore: "{{ nifi_registry_config_dirs.external_config }}/ssl/{{ ansible_fqdn }}.jks"
      nifi.registry.security.keystoreType: JKS
      nifi.registry.security.keystorePasswd: "{{ ansible_hostname }}!"
      nifi.registry.security.keyPasswd: "{{ ansible_hostname }}!"
      nifi.registry.security.truststore: "{{ nifi_registry_config_dirs.external_config }}/ssl/truststore.jks"
      nifi.registry.security.truststoreType: JKS
      nifi.registry.security.truststorePasswd: changeit
      nifi.registry.security.needClientAuth: false
    bootstrap:
      java.arg.2: -Xms4g
      java.arg.3: -Xmx4g
    logback:
      /configuration/appender[@name="APP_FILE"]/rollingPolicy/timeBasedFileNamingAndTriggeringPolicy/maxFileSize: 10MB
      /configuration/appender[@name="APP_FILE"]/rollingPolicy/maxHistory: 5
    identity_providers:
      /identityProviders/provider/identifier: ldap-identity-provider
      /identityProviders/provider/property[@name="Authentication Strategy"]: LDAPS
      /identityProviders/provider/property[@name="Manager DN"]: CN=svc-apache-nifi,OU=Service,OU=Secured Accounts,OU=SPECTRUM,DC=CORP,DC=CHARTERCOM,DC=com
      /identityProviders/provider/property[@name="Manager Password"]: b?]1kv3BB~<7.aLh}80't*\Z
      /identityProviders/provider/property[@name="TLS - Truststore"]: "{{ nifi_registry_config_dirs.external_config }}/ssl/ldap.jks"
      /identityProviders/provider/property[@name="TLS - Truststore Password"]: changeit
      /identityProviders/provider/property[@name="TLS - Truststore Type"]: JKS
      /identityProviders/provider/property[@name="TLS - Protocol"]: TLSv1.2
      /identityProviders/provider/property[@name="Url"]: ldaps://ncechtradlb.corp.chartercom.com:636
      /identityProviders/provider/property[@name="User Search Base"]: OU=Corp Ops Engin _ Tech,OU=Corporate,OU=Accounts,OU=SPECTRUM,DC=CORP,DC=CHARTERCOM,DC=com
      /identityProviders/provider/property[@name="User Search Filter"]: sAMAccountName={0}
      /identityProviders/provider/property[@name="Identity Strategy"]: USE_USERNAME
